### ISSUE TITLE
Problem on Windows

### ISSUE THREAD

**Issue by H4wak** [mogemimi/oh-my-gyp#1]
runnig this command : 
gyp hello.gyp --depth=. -f msvs -G msvs_version=2013

i have : 
'gyp' is not recognized as an internal or external command, operable program or batch file

**Comment by mogemimi** [comment]
Hi @H4wak,

For basic infomation about installing gyp, please visit:
- https://github.com/enginetrouble/gyp-getting-started
- https://github.com/mogemimi/pomdog/wiki/How-to-Install-GYP

Anyway, if you want to install `gyp` as global (not specific to this project) command, please make sure you've tried steps 1 through 3 above.

#### (1) Install GYP on your Windows machine

Windows default command prompt (cmd.exe) and PowerShell:

```
git clone https://chromium.googlesource.com/external/gyp.git C:\path\to\gyp
```

Git Bash (MinGW):

```
git clone https://chromium.googlesource.com/external/gyp.git /c/path/to/gyp
```

#### (2) Set the gyp path environment variable

Windows command prompt:

```
set PATH=%PATH%;C:\path\to\gyp
```

PowerShell:

```
$env:Path += ";C:\path\to\gyp"
```

Git Bash:

```
export PATH="$PATH:/c/path/to/gyp"
```

#### (3) Check if you have installed gyp

```
gyp --help
```

I hope I could help you. Good luck with your project.
